### ISSUE TITLE
Define JSON creation payload

### ISSUE THREAD

**Issue by kaihendry** [unee-t/unit#3]
A data structure needs to be defined like https://github.com/unee-t/invite/blob/master/main.go#L46-L54

**Comment by kaihendry** [comment]
What table are units stored in? Perhaps I can generate the payload structure. E.g.

```
type Product struct {
    ID                int16  `json:"id"`                 // id
    Name              string `json:"name"`               // name
    ClassificationID  int16  `json:"classification_id"`  // classification_id
    Description       string `json:"description"`        // description
    Isactive          int8   `json:"isactive"`           // isactive
    Defaultmilestone  string `json:"defaultmilestone"`   // defaultmilestone
    AllowsUnconfirmed int8   `json:"allows_unconfirmed"` // allows_unconfirmed
}
```

**Comment by franck-boullier** [comment]
There are several steps so that BZ can properly create and configure a new unit:

- Make sure that the table `ut_data_to_create_units` has the data needed so the creation and configuration script works as intended (INSERT).
These data are:
  - `mefe_unit_id` - varchar(256): The MEFE_id for the unit we need to configure in the BZ database
  - `mefe_creator_user_id` - varchar(256): The MEFE_id of the user who has created this unit
  - `bzfe_creator_user_id` - mediumint(9): The BZ user id of the user who has created this unit
  - `classification_id` - smallint(6): the id of the BZ classification for that unit (default value is 2)
  - `unit_name` - varchar(54): A name for the unit (it will be the name used in the BZFE)
  - `unit_description_details` - varchar(500): More information about the unit. This is what we use in the BZFE in the 'description' field
- Once all the data have been inserted in the table `ut_data_to_create_units` we can run the script https://github.com/unee-t/unit/blob/master/sql/unit_create_new.sql
- When the script `unit_create_new.sql` is finished, it returns the BZ id for the newly created unit.

**Comment by franck-boullier** [comment]
> Perhaps I can generate the payload structure.

@kaihendry please don't: this is much more complex than that, just use the table `ut_data_to_create_units` and the script `unit_create_new.sql`

**Comment by kaihendry** [comment]
Ok, so I'm relying on MefeUnitID, MefeCreatorUserID, MefeCreatorUserID, BzfeCreatorUserID, ClassificationID, UnitName & UnitDescriptionDetails to be in the JSON payload.
```
type UtDataToCreateUnit struct {
    IDUnitToCreate         int            `json:"id_unit_to_create"`        // id_unit_to_create
    MefeUnitID             sql.NullString `json:"mefe_unit_id"`             // mefe_unit_id
    MefeCreatorUserID      sql.NullString `json:"mefe_creator_user_id"`     // mefe_creator_user_id
    BzfeCreatorUserID      int            `json:"bzfe_creator_user_id"`     // bzfe_creator_user_id
    ClassificationID       int16          `json:"classification_id"`        // classification_id
    UnitName               string         `json:"unit_name"`                // unit_name
    UnitDescriptionDetails sql.NullString `json:"unit_description_details"` // unit_description_details
    BzCreatedDate          mysql.NullTime `json:"bz_created_date"`          // bz_created_date
    Comment                sql.NullString `json:"comment"`                  // comment
    ProductID              sql.NullInt64  `json:"product_id"`               // product_id
    DeletedDatetime        mysql.NullTime `json:"deleted_datetime"`         // deleted_datetime
    DeletionScript         sql.NullString `json:"deletion_script"`          // deletion_script
}

```

**Comment by franck-boullier** [comment]
> Ok, so I'm relying on MefeUnitID, MefeCreatorUserID, BzfeCreatorUserID, ClassificationID, UnitName & UnitDescriptionDetails to be in the JSON payload.

Yes, if we have this in the table `ut_data_to_create_units` fields
- `mefe_unit_id`
- `mefe_creator_user_id`
- `bzfe_creator_user_id`
- `classification_id`
- `unit_name`
- `unit_description_details`

Then the script `unit_create_new.sql` should work as expected and return the newly created bz ID for the new unit.

**Comment by kaihendry** [comment]
https://s.natalian.org/2018-06-27/unit.mp4
